runtime: python311

env_variables:
  GROQ_API_KEY: "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"

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always

entrypoint: uvicorn api.main:app --host 0.0.0.0 --port $PORT