steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/$PROJECT_ID/ecommerce-llm-pipeline:$COMMIT_SHA',
      '-t',
      'gcr.io/$PROJECT_ID/ecommerce-llm-pipeline:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecommerce-llm-pipeline:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecommerce-llm-pipeline:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'ecommerce-llm-pipeline',
      '--image', 'gcr.io/$PROJECT_ID/ecommerce-llm-pipeline:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '900s',
      '--concurrency', '10',
      '--set-env-vars', 'GROQ_API_KEY=${_GROQ_API_KEY}'
    ]

options:
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

substitutions:
  _GROQ_API_KEY: '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'